### PR TITLE
Modified Login UI

### PR DESCRIPTION
**Pull request by txrp0x9**
### About
This PR modifies the default authorization login user-interface. It also adds the ability to logout once logged in by deleting the saved access token.
_____________________________________________
### Changes
- Extracted the toolbar to a new component
- Changed the whole look of the authorization page
- Added a logout feature to the toolbar which deletes the stored access token and allows you to login again.
_____________________________________________
### Expected Results
The authorization page should look like this:
expected

The Navigation Bar should look like this after logging in:
expected2
______________________________________________
### Testing
- Launch your application locally by follow the steps in the [readme](https://github.com/codeuino/Codebadge/blob/master/README.md)
- Make sure the page looks similar to the one as described above.
- Click on the Login button.
- After logging in make sure the Logout button appears on the navigation bar.
_______________________________________________

### CODE REVIEW

**Comment by shivamluthra** [comment]
Hi! @Torpedo99 , Please prefer posting screenshots for UI based issues' review. You can follow [this template](https://github.com/codeuino/Social-Platform-Donut/blob/master/PR_Template.md).

**Comment by txrp0x9** [comment]
Restyled the AuthView component and extracted toolbar and the login button components. Read PR details for the new look.

**Comment by txrp0x9** [comment]
Changed the fonts to `Playfair Display`, `Roboto` and `Roboto Condensed`.

**Review by ayushnagar123 — APPROVED** [review]

**Comment by jaskiratsingh2000** [comment]
Looks good ✌😉

**Review by shivamluthra — APPROVED** [review]
Appreciable! 🎉

**Pull request merged**
