### PR TITLE
Canvas implementation

### PR DESCRIPTION
**Pull request by 21tcoelho**
Implementation of the canvas for creating new badges.

### CODE REVIEW

**Review by ayushnagar123 — APPROVED** [review]

**Comment by vaibhavdaren** [comment]
use git pull --rebase then cherry pick your commits on top.
Also squash your commits

**Comment by 21tcoelho** [comment]
How would I do that?

**Review by shivamluthra — APPROVED** [review]
Looks fine to me! UI can still be improved overtime though :) Please squash your commits for the PR to be merged @21tcoelho

**Comment by 21tcoelho** [comment]
Thank you, but I’m not sure how to squash commits @shivamluthra

**Comment by 21tcoelho** [comment]
Issue #19

**Pull request merged**
